scrape_configs:
  - job_name: "yomu-spring-boot-koyeb"
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ["verbal-atalanta-moondiverc-c0bd26af.koyeb.app"]
        labels:
          environment: production
          application: yomu-diskusi-forum
